name = "EditBoundary"
uuid = "8d3b5f42-939c-49ed-8524-be595a1aa79b"
authors = ["Miguel Raz Guzmán Macedo <miguelraz@ciencias.unam.mx> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
